# -*- coding: utf-8 -*-
"""GetDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pzf1-aQ-ntYl750RXmm6SgB3f6BskuS4

IMPORT THE DATASET
"""

from google.colab import files
from google.colab import drive
import pandas as pd

# Mounting drive
# This will require authentication : Follow the steps as guided
drive.mount('/content/drive')

# Viewing the data in the folder present from the drive
!ls "/content/drive/My Drive/Fraud_Detection_Model_Data_Mining/"

link = "https://drive.google.com/file/d/11FRKyWKM_QnN6ulEMoc17lVCJjiguMPp/view?usp=sharing"

def getDf(path):
  #path = "/content/drive/My Drive/Fraud_Detection_Model_Data_Mining/creditcard.csv"
  df = pd.read_csv(path)
  #df.head()
  return df

path = "/content/drive/My Drive/Fraud_Detection_Model_Data_Mining/creditcard.csv"
df = pd.read_csv(path)
df.head()